version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway_image
    container_name: shareit-gateway_container
    ports:
      - "8081:8081"
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server_image
    container_name: shareit-server_container
    ports:
      - "9091:9091"
      - "9090:9090"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image: postgres:14-alpine
    container_name: shareit_bd_container
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit